kind: Node


provider:
  name: faas
  provider: faas
  gateway: http://localhost:8080

functions:
  leftpad:
    lang: node
    handler: ./handler
    image: albertomarini/faas-leftpad
spec:
  nodeSelector:
    type=cloud
